spring:
  profiles:
    active: dev
---
server:
  port: 8001
spring:
  application:
    name: USER-PROVIDER
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
---
server:
  port: 8101
spring:
  application:
    name: USER-PROVIDER-TEST
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
---
---
server:
  port: 8002
spring:
  application:
    name: PRODUCT-PROVIDER
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aigou
      username: root
      password: root
  profiles: productdev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
mybatis-plus:
  mapper-locations: classpath:cn/itsource/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.aigou.domain,cn.itsource.aigou.query
---
---
server:
  port: 8102
spring:
  application:
    name: PRODUCT-PROVIDER-TEST
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aigou
      username: root
      password: root
  profiles: producttest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
mybatis-plus:
  mapper-locations: classpath:cn/itsource/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.aigou.domain,cn.itsource.aigou.query
---
server:
  port: 9527
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
  profiles: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527 #在注册中心显示的名称
    prefer-ip-address: true #是否在注册中心显示IP地址
zuul:
  routes:
    wdUser.serviceId: plat-provider
    wdUser.path: /plat/**  #映射路径，找这个路径的就直接映射到serviceId
    product.serviceId: product-provider
    product.path: /product/**  #映射路径，找这个路径的就直接映射到serviceId
  prefix: "/aigou"
  ignored-services: "*"
---
